### ISSUE TITLE
Qt licensing statement

### ISSUE THREAD

**Issue by muesli** [amlwwalker/got-qt#2]
Your README mentiosn Qt not being open source. This is incorrect as Qt is LGPL licensed. Also note the official spelling "Qt" (the all uppercase variant is usually associated with QuickTime).

**Comment by amlwwalker** [comment]
I'm trying to be slightly careful because If I'm honest I find the Qt license a complicated one. I think:

If ur work is open source then u can use Qt fine. If your work is not open source but u dynamically link to Qt, fine. If u statically compile, but open source your work, fine. If u statically compile and charge for ur work, then u need a commercial license.
That's my understanding, don't quote me in court on it, but if u learn something new, please let me know!

**Comment by amlwwalker** [comment]
Will fix casing, thanks!

**Comment by muesli** [comment]
I don't think there's anything particular special about the Qt licensing, you'll have to stick to the LGPL just as you have to with any other dependency released under that license.

The examples you gave also apply to any other LGPL dependency, too.

For more info: https://www1.qt.io/qt-licensing-terms/

**Comment by amlwwalker** [comment]
What makes you say that? I've compiled a statically linked app using therecipe/qt the docker containers

**Comment by muesli** [comment]
Hah, I take it back, it looks like that is "fixed" by now. It used to be a fairly hacky / painful process. Notes: https://github.com/therecipe/qt/issues/230

**Comment by amlwwalker** [comment]
Oh yeah docker makes it a dream! :)

I found this, it seems to be a good way to think about the licensing for Qt apps: https://stackoverflow.com/questions/8760076/commercial-application-using-qt

FYI updated the readme

**Comment by muesli** [comment]
I guess we can close this one then?
